Repository Sayan-Singha/Basic_Coding, pull requests merged in 2022-10, with the labels that each got.

#3 Add client server communication codes
  C++/chat_client.cpp
  C++/chat_server.cpp
Labels: enhancement, hacktoberfest-accepted

#7 Add cross platform client server
  client - Xplatform.cpp
  server - Xplatform.cpp
Labels: enhancement, hacktoberfest-accepted

#9 added a python sorting code
  Python/insertion_sort.py
Labels: hacktoberfest-accepted

#12 Add server code
  Python/SERVER.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#14 Create sort_by_freq.py
  Python/sort_by_freq.py
Labels: hacktoberfest-accepted

#15 Create bucket_sort.cpp
  C++/bucket_sort.cpp
Labels: good first issue, hacktoberfest-accepted
